CREATE TABLE COPY_EMP AS SELECT *FROM EMPLOYEES 
DELETE COPY_EMP
WHERE DEPARMENT_ID=80

DELETE  COPY_EMP
WHERE DEPARTMENT_ID=80


MERGE INTO COPY_EMP  CE 
USING EMPLOYEES E 
ON (CE.EMPLOYEE_ID=E.EMPLOYEE_ID)
WHEN MATCHED THEN
    UPDATE SET
            CE.EMAIL=E.EMAIL,
            CE.PHONE_NUMBER=E.PHONE_NUMBER
WHEN NOT MATCHED THEN 
        INSERT 
        VALUES (E.EMPLOYEE_ID,E.FIRST_NAME,E.LAST_NAME,E.EMAIL,E.PHONE_NUMBER,E.HIRE_DATE,
                E.JOB_ID,E.COMMISSION_PCT,E.MANAGER_ID,E.DEPARTMENT_ID)
