SELECT ID ,NOMBRE,APELLIDO,EDAD
FROM EMPLEADOS 
WHERE EDAD BETWEEN 20 AND 30


SELECT ID ,NOMBRE ,APELLIDO ,ID_DEPARTAMENTO
FROM EMPLEADOS 
WHERE ID_DEPARTAMENTO IS NULL

SELECT E.ID ,E.NOMBRE,E.APELLIDO ,E.ID_DEPARTAMENTO,D.NOMBRE
FROM EMPLEADOS E JOIN DEPARTAMENTOS D
ON E.ID_DEPARTAMENTO(+)= D.ID

SELECT D.ID , D.NOMBRE 
FROM DEPARTAMENTOS D
WHERE D.ID NOT IN (SELECT ID_DEPARTAMENTO 
                   FROM EMPLEADOS
                   WHERE ID_DEPARTAMENTO IS NOT NULL)

SELECT D.NOMBRE ,COUNT (E.ID)
FROM EMPLEADOS E  JOIN DEPARTAMENTOS D
ON E.ID_DEPARTAMENTO(+)=D.ID
GROUP BY D.NOMBRE


SELECT E.SALARIO,E.ID_DEPARTAMENTO ,E.NOMBRE ,D.ID,D.NOMBRE,E.APELLIDO
FROM EMPLEADOS E JOIN DEPARTAMENTOS D
ON E.ID_DEPARTAMENTO=D.ID (+)AND E.SALARIO IN (SELECT MAX(SALARIO)
                                                 FROM EMPLEADOS
                                                 GROUP BY ID_DEPARTAMENTO)
                                                 



SELECT NOMBRE,TO_CHAR(FECHA_INICIO,'DD"-"Mon"-"yy'),TO_CHAR(FECHA_FIN, 'DD"-"Mon"-"yy')
FROM PROYECTOS 
WHERE FECHA_INICIO <=TO_DATE ('31-OCT-14','DD"-"Mon"-"yy') AND FECHA_FIN >=TO_DATE('01-JUL-14','DD"-"Mon"-"yy')


SELECT P.NOMBRE ,COUNT(A.ID_EMPLEADO) 
FROM ASIGNACIONES A JOIN PROYECTOS P
ON A.ID_PROYECTO=P.ID 
JOIN EMPLEADOS E
ON A.ID_EMPLEADO=E.ID
GROUP BY P.NOMBRE
ORDER BY P.NOMBRE


SELECT E.NOMBRE , E.APELLIDO , COUNT (A.ID_EMPLEADO)
FROM ASIGNACIONES A  RIGHT JOIN EMPLEADOS E
ON E.ID=A.ID_PROYECTO
LEFT JOIN PROYECTOS P
ON P.ID=A.ID_PROYECTO
GROUP BY E.NOMBRE, E.APELLIDO

SELECT E.NOMBRE , E.APELLIDO , COUNT(A.ID_PROYECTO )
FROM EMPLEADOS E JOIN ASIGNACIONES A
ON E.ID = A.ID_EMPLEADO
GROUP BY E.NOMBRE, E.APELLIDO

SELECT E.NOMBRE , E.APELLIDO,D.NOMBRE , P.NOMBRE
FROM EMPLEADOS E JOIN DEPARTAMENTOS D
ON D.ID=E.ID_DEPARTAMENTO
JOIN PROYECTPOS P 


SELECT  E.NOMBRE,E.APELLIDO, D.NOMBRE, P.NOMBRE
FROM PROYECTOS P JOIN ASIGNACIONES A
ON P.ID=A.ID_PROYECTO 
RIGHT JOIN EMPLEADOS E
ON E.ID=A.ID_EMPLEADO
LEFT JOIN DEPARTAMENTOS D
ON E.ID_DEPARTAMENTO = D.ID
ORDER BY E.NOMBRE

SELECT P.NOMBRE PROYECTO, NVL(SUM(E.SALARIO), 0) COSTO
FROM ASIGNACIONES A JOIN EMPLEADOS E
ON A.ID_EMPLEADO = E.ID
RIGHT JOIN PROYECTOS P
ON A.ID_PROYECTO = P.ID
GROUP BY P.NOMBRE
ORDER BY P.NOMBRE;


SELECT D.ID ,D.NOMBRE,E.ID,P.NOMBRE
FROM DEPARTAMENTOS D JOIN EMPLEADOS E
ON D.ID =E.ID_DEPARTAMENTO
JOIN ASIGNACIONES A
ON A.ID_EMPLEADO= E.ID
JOIN PROYECTOS P
ON P.ID=A.ID_PROYECTO distinct COUNT(SELECT P.NOMBRE FROM 
                                      PROYECTOS 


SELECT D.NOMBRE 
FROM EMPLEADOS E JOIN DEPARTAMENTOS D
ON E.ID_DEPARTAMENTO = D.ID
JOIN (SELECT DISTINCT COUNT(ID_EMPLEADO)
      FROM ASIGNACIONES 
      GROUP BY ID_PROYECTO) CONTADOR



SELECT  E.NOMBRE  ,E.SALARIO 
FROM EMPLEADOS E JOIN ASIGNACIONES A
ON E.ID=A.ID_EMPLEADO (+)AND E.SALARIO IN (SELECT MAX(SALARIO)
                                                 FROM EMPLEADOS)
JOIN PROYECTOS P 
ON A.ID_PROYECTOS  = P.PROYECTOS
