SELECT  COUNTRY_ID, COUNT(REGION_ID) FROM COUNTRIES GROUP BY  REGION_ID ,COUNTRY_ID

SELECT COUNT(MANAGER_ID) CANTIDAD,LOCATION_ID,DEPARTMENT_NAME  FROM DEPARTMENTS GROUP BY  LOCATION_ID,DEPARTMENT_NAME


SELECT COUNT(MANAGER_ID) MANAGER,DEPARTMENT_ID, FROM EMPLOYEES GROUP BY DEPARTMENT_ID 


SELECT  AVG (SALARY) FROM EMPLOYEES WHERE  JOB_ID IN ('IT_PROG','SA_MAN','SA_REP') GROUP BY JOB_ID  


SELECT MIN(SALARY) , MAX(SALARY) , DEPARTMENT_ID FROM EMPLOYEES HAVING MAX(SALARY)>15000 AND MIN(SALARY)<5000



SELECT JOB_ID,MAX(TRUNC (MONTHS_BETWEEN(SYSDATE,HIRE_DATE)/12))
FROM EMPLOYEES
GROUP BY JOB_ID

