SELECT FIRST_NAME FROM EMPLOYEES WHERE FIRST_NAME LIKE 'A%'

SELECT FIRST_NAME FROM EMPLOYEES WHERE LENGTH(FIRST_NAME)<5

SELECT EMPLOYEE_ID ,TO_NUMBER(TO_CHAR (HIRE_DATE,'fm yyyy'))AS HIRE_DATE FROM EMPLOYEES 
WHERE (TO_NUMBER(TO_CHAR (HIRE_DATE,'fm yyyy')) -2017)>10


SELECT EMPLOYEE_ID, COMMISSION_PCT FROM EMPLOYEES WHERE COMMISSION_PCT <0.1 OR COMMISSION_PCT=NULL
