SELECT EMPLOYEE_ID ,FIRST_NAME, LAST_NAME FROM  EMPLOYEES WHERE EMPLOYEE_ID= 60

SELECT EMPLOYEE_ID , DEPARTMENT_ID,SALARY,(SALARY * COMMISSION_PCT)
FROM EMPLOYEES
WHERE DEPARTMENT_ID=80
AND JOB_ID='SA_MAN'

SELECT MANAGER_ID , DEPARTMENT_ID,EMPLOYEE_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID=30 AND DEPARTMENT_ID=50 OR DEPARTMENT_ID=100

SELECT * FROM COUNTRIES WHERE COUNTRY_NAME LIKE '%e%' OR COUNTRY_NAME LIKE '%i%'

SELECT JOB_ID ,MAX_SALARY, MIN_SALARY , MAX_SALARY-MIN_SALARY FROM JOBS 
