4.-
select id.nombre
FROM departamentos
where id not in (select id_departamento
                 from empleados 
                 where id_departamento is not null)
order by ID


6.-
SELECT IE.INTERVALO , COUNT (IE.INTERVALO) NUM_EMPLEADOS 
FROM (SELECT CASE WHEN EDAD <16 THEN '< 16'
                  WHEN EDAD DETWEEN 16 AND 25 THEN '16 A 25'
                  WHEN EDAD DETWEEN 26 AND 40 THEN '16 A 25'
                  WHEN EDAD >40 THEN '< 40'
            END INTERVALO 
    FROM EMPLEADOS ) IE 
    GROUP BY IE.INTERVALO 
    ORDER BY CASE INTERVALO  WHEN '< 16' THEN 1
                             WHEN '16 A 25' THEN 2
                             WHEN '26 A 40' THEN 3
                             WHEN '40 > ' THEN 4
    END 



7.-
    SELECT 'M' GENERO,COUNT(GENERO ) NUM_EMPLEADOS
    FROM  EMPLEADOS 
    WHERE GENERO='M'
    UNION 
    SELECT 'F' ,COUNT(GENERO)
    FROM EMPLEADOS
    WHERE GENERO='F'
    ORDER BY GENERO DESC 


8.-
SELECT FECHAS_INICIO, FECHA_FINAL 
FROM PROYECTOS 
WHERE FECHA_INICIO <="31-10-14" AND FECHA_FIN >='01-07-14'



13.-
SELECT P.NOMBRE NVL(CPP.C,0) COSTO 
FROM PROYECTOS 
LEFT JOIN (SELECT A.ID_PROYECTO ,SUM(E.SALARIO)
           FROM ASIGNACIONES A 
           JOIN EMPLEADOS E 
           ON A.ID_EMPLEADO=E.ID
           GROUP BY ID_PROYECTO)CPP
ON P.ID=CPP.ID_PROYECTO
ORDER BY P.NOMBRE 

14.-
SELECT D.NOMBRE ,NVL(NPPD.NP,0) NUM_PROYECTOS
FROM DEPARTAMENTOS D 
LEFT JOIN (SELECT E.ID ,COUNT(DISTINCT A.ID_PROYECTO)NP
           FROM ASIGNACIONES A 
           JOIN EMPLEDOS E 
           ON A.ID_EMPLEADO=E.ID
           GROUP BY E.ID_DEPARTAMENTO)NPPD
ON D.ID=NPPD.ID_DEPARTAMENTO
ORDER BY D.NOMBRE 

15.-
SELECT P.NOMBRE ,E.NOMBRE ,MSPP.MASKED
FROM (SELECT A.ID_PROYECTOS , MAX(E.SALARIO) MS 
      FROM ASIGNACIONES A 
      JOIN EMPLEADOS E 
      ON A.ID_EMPLEADO=E.ID
      GROUP BY ID_PROYECTO) MSPP
JOIN ASIGNACIONES A 
ON MSPP.ID_PROYECTO = A.ID_PROYECTO
AND E.SALARIO=MSPP.MS 
RIGHT JOIN PROYECTOS P 
ON P.ID=A.ID_PROYECTO
ORDER BY P.NOMBRE 





