SELECT DEPARTMENT_NAME
FROM DEPARTMENTS
WHERE MANAGER_ID =(SELECT MANAGER_ID ,FIRST_NAME
                      FROM EMPLOYEES 
                      WHERE MANAGER_ID IN (SELECT  EMPLOYEE_ID
                                           FROM EMPLOYEES))
                
SELECT E.EMPLOYEE_ID,  E.MANAGER_ID , E.FIRST_NAME,E.LAST_NAME , D.DEPARTMENT_NAME
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.EMPLOYEE_ID=D.MANAGER_ID(+)
ORDER BY D.DEPARTMENT_NAME

SELECT W.EMPLOYEE_ID, W.LAST_NAME||' '||W.FIRST_NAME,
       M.MANAGER_ID ,M.LAST_NAME||' '||M.FIRST_NAME
FROM EMPLOYEES W JOIN EMPLOYEES M
ON M.EMPLOYEE_ID=W.MANAGER_ID
AND W.COMMISSION_PCT<=0.15
ORDER BY W.EMPLOYEE_ID


SELECT E.FIRST_NAME ,E.LAST_NAME, 
       J.JOB_TITLE,
       TO_CHAR(H.START_DATE,'fm DD"-" Mon"-" YYYY'),TO_CHAR(H.END_DATE,'fm DD "-" Mon "-" YYYY')
FROM EMPLOYEES E, JOB_HISTORY H, JOBS J
WHERE E.EMPLOYEE_ID=H.EMPLOYEE_ID 
AND   H.JOB_ID=J.JOB_ID
ORDER BY E.FIRST_NAME

SELECT D.DEPARTMENT_NAME,L.STREET_ADDRESS, C.COUNTRY_NAME,R.REGION_NAME
FROM DEPARTMENTS D, LOCATIONS L , REGIONS R ,COUNTRIES C
WHERE  D.LOCATION_ID =L.LOCATION_ID
AND L.COUNTRY_ID=C.COUNTRY_ID
AND C.REGION_ID=R.REGION_ID
ORDER BY D.DEPARTMENT_NAME

SELECT E.FIRST_NAME,E.LAST_NAME ,E.DEPARTMENT_ID
FROM EMPLOYEES E
JOIN (SELECT DEPARTMENT_ID ,COUNT (EMPLOYEE_ID)
      FROM EMPLOYEES 
      WHERE DEPARTMENT_ID IS NOT NULL
      GROUP BY DEPARTMENT_ID
      HAVING COUNT (DEPARTMENT_ID) < 6)NEPD             
ON E.DEPARTMENT_ID=NEPD.DEPARTMENT_ID
ORDER BY E.DEPARTMENT_ID


SELECT E.DEPARTMENT_ID ,E.FIRST_NAME,E.LAST_NAME
FROM EMPLOYEES E
WHERE E.DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
                          FROM EMPLOYEES
                          WHERE DEPARTMENT_ID IS NOT NULL
                          GROUP BY DEPARTMENT_ID
                          HAVING COUNT (EMPLOYEE_ID)<6)
                          
SELECT E.DEPARTMENT_ID,E.FIRST_NAME ,E.LAST_NAME 
FROM EMPLOYEES E 
WHERE (E.DEPARTMENT_ID,0)IN (SELECT DEPARTMET_ID ,COUNT (EMPLOYEE_ID)*0
                              FROM EMPLOYEES
                              WHERE DEPARTMENT_ID IS NOT NULL 
                              GROUP BY DEPARTMENT_ID 
                              HAVING COUNT (EMPLOYEE_ID)<6)
