SELECT EMPLOYEE_ID , LAST_NAME ,FIRST_NAME, SALARY,TRUNC(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)/12)
FROM EMPLOYEES
WHERE SALARY > (SELECT TRUNC( AVG(SALARY))
                FROM EMPLOYEES)
AND TRUNC(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)/12) <10              



SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,DEPARTMENT_ID
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
WHERE   DEPARTMENT_ID = (SELECT DEPARTMENT_ID 
                         FROM  DEPARTMENTS WHERE DEPARTMENT_NAME LIKE 'A%')



SELECT COUNTRY_ID,REGION_ID
FROM COUNTRIES 
WHERE REGION_ID=(SELECT REGION_ID 
                 FROM REGIONS 
                 WHERE LOWER(REGION_NAME) LIKE '%america%')


SELECT EMPLOYEE_ID, FIRST_NAME , LAST_NAME 
FROM EMPLOYEES
WHERE MANAGER_ID IN (SELECT EMPLOYEE_ID
                     FROM EMPLOYEES
                     WHERE SALARY=(SELECT MAX(SALARY)
                                   FROM EMPLOYEES
                                   WHERE EMPLOYEE_ID IN (SELECT DISTINCT MANAGER_ID
                                                         FROM EMPLOYEES
                                                         WHERE MANAGER_ID IS NOT NULL  )))                            
ORDER BY EMPLOYEE_ID




SELECT EMPLOYEE_ID,FIRST_NAME ,LAST_NAME, DEPARTMENT_ID 
FROM EMPLOYEES
WHERE  DEPARTMENT_ID  IN (SELECT DEPARTMENT_ID 
                          FROM DEPARTMENTS
                          WHERE LOWER(DEPARTMENT_NAME)LIKE '%shipping%')
AND JOB_ID IN (SELECT JOB_ID
              FROM JOBS 
              WHERE LOWER(JOB_TITLE)LIKE '%shipping%')
ORDER BY EMPLOYEE_ID 


SELECT E.EMPLOYEE_ID,E.LAST_NAME,
       D.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM EMPLOYEES E , DEPARTMENTS D
WHERE E.DEPARTMENT_ID= D.DEPARTMENT_ID
ORDER BY E.EMPLOYEE_ID



SELECT E.EMPLOYEE_ID,E.LAST_NAME,
        D.DEPARTMENT_ID,D.DEPARTMENT_NAME,
        L.LOCATION_ID ,L.STREET_ADDRESS
FROM EMPLOYEES E , DEPARMENTS D, LOCATIONS L
WHERE E.DEPARMENT_ID =D.DEPARMENT_ID
AND   D.LOCATION_ID = L.LOCATION_ID
ORDER BY E.EMPLOYEE_ID
--INNER JOIN SOLO MUESTRA LAS CONDICONES JOIN ESPECIFICADAS 


-->LEFT OUTER JOIN  PERMITEN QUE SIN QUE LA CONDICION NO ESTA DECLARADA PUEDE SER MOSTRADA SE REPRESENTA CON (+)
SELECT E.EMPLOYEE_ID,E.LAST_NAME,
        D.DEPARTMENT_ID,D.DEPARTMENT_NAME,
        L.LOCATION_ID ,L.STREET_ADDRESS
FROM EMPLOYEES E , DEPARMENTS D, LOCATIONS L
WHERE E.DEPARMENT_ID =D.DEPARMENT_ID(+)
AND   D.LOCATION_ID = L.LOCATION_ID
ORDER BY E.EMPLOYEE_ID 

-->RIGTH OUTER JOIN SOLO LOS DE LA DERECHA SE REPRESENTA 
SELECT E.EMPLOYEE_ID,E.LAST_NAME,
        D.DEPARTMENT_ID,D.DEPARTMENT_NAME,
        L.LOCATION_ID ,L.STREET_ADDRESS
FROM EMPLOYEES E , DEPARMENTS D, LOCATIONS L
WHERE E.DEPARMENT_ID(+) =D.DEPARMENT_ID
AND   D.LOCATION_ID = L.LOCATION_ID
ORDER BY E.EMPLOYEE_ID
--> FULL OUTHER JOIN 

SELECT E.EMPLOYEE_ID, E.LAST_NAME,
        D.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM EMPLOYEES E , DEPARMENTS D, LOCATIONS L
ON  E.DEPARMENT_ID=D.DEPARMENT_ID
ORDER BY E.EMPLOYEE_ID
-----------------------------------------------------------------
--LEFT JOIN

SELECT E.EMPLOYEE_ID, E.LAST_NAME,
        D.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM EMPLOYEES E LEFT JOIN  DEPARMENTS D
ON  E.DEPARMENT_ID=D.DEPARMENT_ID
ORDER BY E.EMPLOYEE_ID
--RIGHT JOIN 
SELECT E.EMPLOYEE_ID, E.LAST_NAME,
        D.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM EMPLOYEES E RIGHT JOIN  DEPARMENTS D
ON  E.DEPARMENT_ID=D.DEPARMENT_ID
ORDER BY E.EMPLOYEE_ID
-- FULL JOIN 
SELECT E.EMPLOYEE_ID, E.LAST_NAME,
        D.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM EMPLOYEES E FULL JOIN  DEPARMENTS D
ON  E.DEPARMENT_ID=D.DEPARMENT_ID
ORDER BY E.EMPLOYEE_ID



---NATUAL JOIN TOMA TODOS LOS VALORES QUE SEAN IGUALES DE LAS COLUMNAS SELECIONADAD INCLUYENDO 
--EL TIPO DE DATO LAS UNE INDISTINTAMENTE SIN NESECIDAD DE IMPLEMENTAR MAS SENTENCIAS 

SELECT DEPARTMENT_NAME , MANAGER_ID,DEPARTMENT_ID,EMPLOYEE_ID,LAST_NAME
FROM DEPARTMENTS NATURAL JOIN EMPLOYEES